title: Yichen Luo
description: Personal homepage of Yichen Luo
sourcecode: "https://github.com/gchauras/much-worse-jekyll-theme"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "http://www.yichen-luo.com/"     # the base hostname & protocol for your site
baseurl: "/"                   # the subpath of your site, e.g. /blog

author:
    name: Yichen Luo
    facebook: Yichen Luo
    scholar: Yichen Luo
    email: usesy34@ucl.ac.uk
    github_username: lyc0603
    linkedin: luo-yichen-8aba91245
    

# Build settings
markdown: kramdown
highlighter: rouge

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
    provider:
    statcounter:
        sc_project  :
        sc_security :
        sc_invisible: 1
        sc_text     : 2
    google:
        tracking_id: ''
    getclicky:
      site_id:
    mixpanel:
        token: ''
    piwik:
        baseURL: '' # Piwik installation address (without protocol)
        idsite: ''  # the id of the site on Piwik

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
    provider:
    disqus:
      short_name:
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light
